### ISSUE TITLE
Not able to use your plugin

### ISSUE THREAD

**Issue by simogeo** [CPPL/grav-bigfootjs#1]
hey @raigsOverItAll

Thanks for your plugin. I tried it today but I'm not able to activate it. See example online : 
http://www.intermezzo-coop.eu/actualites/reduire-lespace-publicitaire-pour-lutter-contre-le-rechauffement-climatique

I set system.yaml as following : 

```
  markdown:
    extra: true
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
```

Any clue ?
